baseurl = "https://www.varunmangalick.com/"
title = "Varun Mangalick"
copyright = "Copyright &copy; 202- do people even read these?"
canonifyurls = true
theme = "hugo-kiera-varun"
themesDir = "themes"

paginate = 10

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
pluralizelisttitles = false

[author]
    name = "Varun Mangalick"

[[menu.main]]
    name = "Home" 
    weight = 10 
    url = "/" 
    identifier = "home"
[[menu.main]]
    name = "Projects" 
    weight = 20 
    url = "/projects/" 
    identifier = "projects"
[[menu.main]]
    name = "Travel" 
    weight = 30 
    url = "/travel/" 
    identifier = "travel"
[[menu.main]]
    name = "Life" 
    weight = 40 
    url = "/life/" 
    identifier = "life"
[[menu.main]]
    name = "Art" 
    weight = 50 
    url = "/art/" 
    identifier = "art"


[taxonomies]
  category = "categories"
